# Generated by Django 3.0.8 on 2020-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('wo', 'world'), ('env', 'environment'), ('tech', 'technology'), ('des', 'design'), ('cul', 'culture'), ('bus', 'business'), ('pol', 'politics'), ('op', 'opinion'), ('sci', 'science'), ('hea', 'health'), ('sty', 'style'), ('tra', 'travel')], default='wo', max_length=50),
        ),
    ]
