# Generated by Django 2.2.12 on 2020-07-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200705_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('wor', 'world'), ('env', 'environment'), ('tech', 'technology')], default='wor', max_length=50),
        ),
    ]
