# Generated by Django 2.2.12 on 2020-07-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200705_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('WORLD', 'world'), ('ENVIRONMENT', 'environment'), ('TECHNOLOGY', 'technology')], default='WORLD', max_length=50),
        ),
    ]
