# Generated by Django 2.2.12 on 2020-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200705_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('WORLD', 'world'), ('ENVIRONMENT', 'environment'), ('TECHNOLOGY', 'technology'), ('DESIGN', 'design'), ('CULTURE', 'culture'), ('POLITICS', 'politics'), ('BUSINESS', 'business'), ('OPINION', 'opinion'), ('SCIENCE', 'science'), ('HEALTH', 'health'), ('STYLE', 'style'), ('TRAVEL', 'travel')], default='WORLD', max_length=50),
        ),
    ]
